apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.appSetName }}
  namespace: openshift-gitops
spec:
  generators:
    # matrix 'parent' generator
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: a
          - list:
              elements:
              - applicationurl: 'https://github.com/michaelkotelnikov/argocd-bench-list-generator.git'
                apppath: list-app-19
                apptargetrevision: master
                valuesFiles: 'values.yaml'
              - applicationurl: 'https://github.com/IdanHenik/distributed-argocd-demo.git'
                apppath: apps/apps/openshift-gitops
                apptargetrevision: master
              - applicationurl: 'https://github.com/IdanHenik/distributed-argocd-demo.git'
                apppath: apps/apps/generic-policy
                apptargetrevision: master
  template:
    metadata:
      name: '{{ .Values.projectName }}-{{ "{{ name }}" }}-{{ "{{ metadata.labels.env }}" }}'
    spec:
      project: default
      sources:
        - repoURL: '{{ "{{applicationurl}}" }}'
          path: '{{ "{{apppath}}" }}'
          targetRevision: '{{ "{{appptargetrevision}}" }}'
          helm:
            valueFiles:
            - '{{ "{{valuesFiles}}" }}'
            parameters:
              - name: global.envName
                value: '{{ "{{ metadata.labels.env }}" }}'
      destination:
        name: 'in-cluster'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
