apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: {{ .Values.appSetName }}
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: flavor-c
  template:
    metadata:
      name: '{{ .Values.projectName }}-{{ "{{ name }}" }}-{{ "{{ metadata.labels.env }}" }}'
    spec:
      project: default
      sources:
        - repoURL: 'https://github.com/michaelkotelnikov/argocd-bench-list-generator.git'
          path: list-app-20
          targetRevision: master
          helm:
            valueFiles:
            - 'values.yaml'
            parameters:
              - name: global.envName
                value: '{{ "{{ metadata.labels.env }}" }}'
      destination:
        name: 'in-cluster'
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
